/**
 * Data for the `/portfolio-map` experience. Fully decoupled from
 * `lib/data.ts` — this feature owns its own types and content.
 *
 * Photography comes from `projectImages.json`, generated by
 * `scripts/optimize-project-photos.mjs` from the client's raw photo drop
 * (untracked; only the optimized WebP derivatives under
 * `public/images/projects/` are committed). Re-run that script after adding or
 * replacing a raw photo and the lists below pick the change up automatically.
 *
 * Every entry below has photography. The `CARD_GRADIENT` fallback in the card
 * and modal still covers an empty `images` array for any future addition that
 * lands before its photos do.
 *
 * Awaiting client details before they can go live: `beer-store` (14 photos) and
 * `tamas` (13 photos) are optimized and sitting in `public/images/projects/`,
 * but have no city, address, or project type from the client yet. Add a
 * PROJECTS entry for each once that comes back.
 */

import projectImages from "./projectImages.json";

export type ProjectCategory =
  | "Luxury Retail"
  | "Commercial"
  | "Special Project";

export interface ProjectImage {
  src: string; // public path, e.g. /images/projects/isaia/isaia-1.webp
  width: number;
  height: number;
}

export interface PortfolioCity {
  key: string;
  name: string; // full name, used in the city list and headings
  shortLabel: string; // short map-chip label, e.g. "TORONTO"
  x: number; // position in the 780×450 map viewBox
  y: number;
  labelDir: "left" | "right"; // which side the default (unzoomed) label chip opens toward
}

export interface PortfolioProject {
  id: number;
  slug: string; // matches the public/images/projects/<slug>/ folder
  name: string;
  category: ProjectCategory;
  city: string; // PortfolioCity.key
  location: string; // short display line under the project name
  address: string; // full street address, "" when not supplied by the client
  projectType: string; // the client's own description of the scope
  description: string;
  images: ProjectImage[]; // empty = no photography yet, card falls back to a gradient
  placeholder: boolean; // true = demo/placeholder content, not a real completed project yet
}

const IMAGES = projectImages as Record<string, ProjectImage[]>;

/** Photo set for one or more slugs, concatenated in the order given. */
function imagesFor(...slugs: string[]): ProjectImage[] {
  return slugs.flatMap((slug) => IMAGES[slug] ?? []);
}

// x/y are projected with `scripts/gen-portfolio-map-path.mjs` (d3-geo conic
// conformal, same pipeline as LAND_PATH) — not hand-placed. Every GTA project
// projects to within ~2px of the same point, so Toronto, Yorkville, Aurora,
// Scarborough and Mississauga all cluster under the one `gta` key.
export const CITIES: PortfolioCity[] = [
  { key: "gta", name: "Greater Toronto Area", shortLabel: "TORONTO", x: 495, y: 233, labelDir: "left" },
  { key: "calgary", name: "Calgary Area", shortLabel: "CALGARY", x: 240, y: 157, labelDir: "right" },
  { key: "poconos", name: "Pocono Mountains", shortLabel: "POCONOS", x: 533, y: 254, labelDir: "right" },
  { key: "sevierville", name: "Sevierville", shortLabel: "SEVIERVILLE", x: 476, y: 322, labelDir: "right" },
  { key: "austin", name: "Austin Area", shortLabel: "AUSTIN", x: 353, y: 391, labelDir: "left" },
  { key: "miami", name: "Miami", shortLabel: "MIAMI", x: 526, y: 426, labelDir: "right" },
];

export const CATEGORIES: ProjectCategory[] = [
  "Luxury Retail",
  "Commercial",
  "Special Project",
];

export const PROJECTS: PortfolioProject[] = [
  {
    id: 6,
    slug: "isaia",
    name: "Isaia",
    category: "Luxury Retail",
    city: "gta",
    location: "77 Yorkville Ave, Toronto",
    address: "77 Yorkville Ave, Toronto, ON M5R 1C1",
    projectType:
      "Isaia S.p.A, luxury men's retail/suit store, full retail buildout in Yorkville",
    description:
      "Isaia S.p.A.'s Yorkville store. A full retail build-out for the Italian menswear house, finished to its own store specification.",
    images: imagesFor("isaia"),
    placeholder: false,
  },
  {
    id: 7,
    slug: "digicast",
    name: "Digicast",
    category: "Commercial",
    city: "gta",
    location: "415 Yonge St, Toronto",
    address: "415 Yonge St Ste 1800, Toronto, ON M5B 2E7",
    projectType:
      "Digicast Inc., telecommunications/broadcasting, staff office and streaming studio buildout",
    description:
      "Staff offices and a streaming studio for Digicast Inc., a broadcast and telecommunications company on Yonge Street.",
    images: imagesFor("digicast"),
    placeholder: false,
  },
  {
    id: 8,
    slug: "elm-spa",
    name: "Elm Spa",
    category: "Commercial",
    city: "gta",
    location: "557 Church St, Toronto",
    // The client's email gave 415 Yonge St Ste 1800 here, but that's Digicast's
    // address (id 7, listed directly above it in the same email) — a paste slip.
    // This address is elmspa's own published one; confirm with the client.
    // Not Elmwood Spa: a sister location under the same ownership, being
    // worked on separately.
    address: "557 Church St, 3rd Floor, Toronto, ON M4Y 2E2",
    projectType: "Spa renovation",
    description:
      "A full spa renovation for the owners of Elmwood Spa, at a separate Toronto location.",
    images: imagesFor("elm-spa"),
    placeholder: false,
  },
  {
    id: 9,
    slug: "salon-city",
    name: "Salon City",
    category: "Commercial",
    city: "gta",
    location: "14800 Yonge St, Aurora",
    address: "14800 Yonge St Unit 118, Aurora, ON L4G 1N3",
    projectType:
      "Suite-rental space for independent beauty and salon entrepreneurs, full spa buildout",
    description:
      "Suite-rental space in Aurora for independent beauty and salon professionals, taken from bare unit to finished suites.",
    images: imagesFor("salon-city"),
    placeholder: false,
  },
  {
    id: 10,
    slug: "shn",
    name: "Scarborough Health Network",
    category: "Special Project",
    city: "gta",
    location: "3050 Lawrence Ave E, Scarborough",
    address: "3050 Lawrence Ave E, Scarborough, ON M1P 2V5",
    projectType:
      "Scarborough Health Network General Hospital, sound mitigation and air intake extension",
    description:
      "Sound mitigation and an air-intake extension at Scarborough Health Network General Hospital, carried out on a working hospital campus.",
    images: imagesFor("shn-intake", "shn-walls", "shn-windows"),
    placeholder: false,
  },
  {
    id: 11,
    slug: "toronto-showroom",
    name: "Toronto Showroom",
    category: "Commercial",
    city: "gta",
    location: "4080 Confederation Pkwy, Mississauga",
    address: "4080 Confederation Pkwy, Mississauga, ON",
    projectType: "Cole Haan corporate showroom, full office/showroom buildout",
    description:
      "Cole Haan's corporate showroom in Mississauga, with staff offices built out alongside the display space.",
    images: imagesFor("toronto-showroom"),
    placeholder: false,
  },
  {
    id: 12,
    slug: "crossiron-mills",
    name: "CrossIron Mills",
    category: "Luxury Retail",
    city: "calgary",
    location: "Rocky View County, AB",
    address: "261055 Crossiron Blvd, Rocky View County, AB T4A 0G3",
    projectType: "Cole Haan outlet, retail buildout",
    description:
      "A Cole Haan outlet at CrossIron Mills, north of Calgary, built out in full by Rose Hill Design Build.",
    images: imagesFor("crossiron-mills"),
    placeholder: false,
  },
  {
    id: 13,
    slug: "pocono-mountains",
    name: "Pocono Mountains",
    category: "Luxury Retail",
    city: "poconos",
    location: "Tannersville, PA",
    address: "1000 Premium Outlets Dr Ste E-01, Tannersville, PA 18372",
    projectType: "Cole Haan outlet, retail buildout",
    description:
      "A Cole Haan outlet at the Tannersville outlet centre in the Poconos, finished to the brand's retail standard.",
    images: imagesFor("pocono-mountains"),
    placeholder: false,
  },
  {
    id: 14,
    slug: "sevierville",
    name: "Sevierville",
    category: "Luxury Retail",
    city: "sevierville",
    location: "Sevierville, TN",
    address: "1645 Parkway, Suite 750, Sevierville, TN 37862",
    projectType: "Cole Haan outlet, retail buildout",
    description:
      "A Cole Haan outlet on the Parkway in Sevierville, Tennessee, fitted out start to finish.",
    images: imagesFor("sevierville"),
    placeholder: false,
  },
  {
    id: 15,
    slug: "round-rock",
    name: "Round Rock",
    category: "Luxury Retail",
    city: "austin",
    location: "Round Rock, TX",
    address: "4401 N Interstate Hwy 35 Ste 537, Round Rock, TX 78664",
    projectType: "Cole Haan outlet, retail buildout",
    description:
      "A Cole Haan outlet at Round Rock, just north of Austin, taken from demolition through to handover.",
    images: imagesFor("round-rock"),
    placeholder: false,
  },
  {
    id: 16,
    slug: "coral-gables",
    name: "Coral Gables",
    category: "Luxury Retail",
    city: "miami",
    location: "Coral Gables, FL",
    address: "350 San Lorenzo Ave Ste 2137, Coral Gables, FL 33146",
    projectType: "Cole Haan inline, retail buildout",
    description:
      "Cole Haan's inline store in Coral Gables, Florida. Retail build-out throughout.",
    images: imagesFor("coral-gables"),
    placeholder: false,
  },
];

export const CATEGORY_COLOR: Record<ProjectCategory, string> = {
  "Luxury Retail": "var(--color-gold)",
  Commercial: "var(--color-medium-grey)",
  "Special Project": "var(--color-gold-light)",
};

// Card/modal fallback for projects with no photography yet (`images: []`).
export const CARD_GRADIENT: Record<ProjectCategory, string> = {
  "Luxury Retail": "linear-gradient(135deg, var(--color-dark), var(--color-gold))",
  Commercial:
    "linear-gradient(135deg, var(--color-gold-contrast), var(--color-medium-grey))",
  "Special Project":
    "linear-gradient(135deg, var(--color-gold), var(--color-dark))",
};
